spring.application.name=alms-pro
server.port=8080

spring.datasource.url=jdbc:mysql://yamabiko.proxy.rlwy.net:49792/alms_pro?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=fJkaHnKJcynXLGOHVIZuneVfSpEvMxwq
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=6A576D5A7134743777217A25432A462D4A614E645267556B58703273357638792F423F4528482B4D6251655368566D59713374367739792442264528472B4B6250
jwt.expiration=86400000

cors.allowed-origins=http://localhost:3000,http://localhost:5173,https://alms-pro-app.vercel.app

alms.block-size=10
alms.default-building-id=1
